import './tests/globals';
import './tests/ast_binary_operator_node_tests';
import './tests/ast_build_tests';
import './tests/ast_build/tree_part_build_tests';
import './tests/ast_fringe_node_tests';
import './tests/ast_incomplete_binary_node_tests'
import './tests/interpreter_tests';
import './tests/persistent_stack_tests';
import './tests/tokenization_tests';
import './tests/tokenization/character_class_tests';
import './tests/tokenization/character_crawler_tests';
import './tests/tokenization/crawl_strategies_tests';
