name: 'Specs'
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.13.1

      - name: run specs
        run: |
          npm install \
          npm run build_for_tests \
          npm run test
